### ISSUE TITLE
Allow deriving onto a struct

### ISSUE THREAD

**Issue by Milo123459** [Lucretiel/autodefault#3]
This would be useful so that every time the struct is called, autodefault automatically applies itself to it.

**Comment by zetanumbers** [comment]
I think i know what you are talking about, so let me explain a problem. `#[derive(Autodefault)` is not possible unless the struct instantiation is inside of another macro, like `#[autodefault]` on a function or hypothetical `autodefault! {}`. You could imagine if struct from a 3rd party crate could modify your code without any macro invocations on your side, that would be a bit chaotic for a programming language.

Perhaps there're some improvements to be made, but not as i understand this issue.

**Comment by Lucretiel** [comment]
I'm not really sure what you mean by this– `autodefault` modifies the syntax of struct initialization; it doesn't have anything to do with the type.

**Comment by Milo123459** [comment]
This is something I propose to happen:
```rs
#[derive(Default, AutoDefault)]
struct Hello {
     name: String,
     likes: Option<Vec<String>>
}

Hello {
    name: String::from("hello!")
    // autodefault does its thing here
}
```

**Comment by zetanumbers** [comment]
Sorry, that's not possible.

**Comment by Lucretiel** [comment]
Yeah, that's unfortunately not possible. `autodefault` works by rewriting struct expressions during compilation to insert the `..Default::default()`; it isn't a property of the type.
